### ISSUE TITLE
Mudar formato de respostas e trechos bíblicos

### ISSUE THREAD

**Issue by sergioSHKLR** [sergioSHKLR/1lde#16]
@JhonnyBn, considero que tanto as respostas dos Espíritos quanto os trechos bíblicos merecem destaque, usando o mesmo (ou similar) padrão para denotar correlação.

No original temos aspas. E em nossa versão, com a mudança mais recente que gostaria de implementar, teríamos uma redundância visual quádrupla:

1. aspas
2. blockquote
3. italico
4. situada entre linhas em branco

Que acha disso? Excessivo? Qual seria a formatação mais adequada para que este destaque visual não se perdesse quando conversões fossem feitas para outros tipos de arquivos?

**Comment by JhonnyBn** [comment]
> @JhonnyBn, considero que tanto as respostas dos Espíritos quanto os trechos bíblicos merecem destaque, usando o mesmo (ou similar) padrão para denotar correlação.

Concordo. Só acho importante haver diferença entre respostas dos espíritos e trechos bíblicos para no futuro conseguirmos fazer aquele red letter

> No original temos aspas. E em nossa versão, com a mudança mais recente que gostaria de implementar, teríamos uma redundância visual quádrupla:
> 
> 1. aspas
> 2. blockquote
> 3. italico
> 4. situada entre linhas em branco
> 
> Que acha disso? Excessivo? Qual seria a formatação mais adequada para que este destaque visual não se perdesse quando conversões fossem feitas para outros tipos de arquivos?

Considero que o livro aqui deve se aproximar do livro, com pequenas mudanças para melhorar o visual nesse formato digital. Se essas mudanças tiverem sentido sintático (como por exemplo, `*` em markdown indica negrito, é um item sintático) ou melhoram o visual, ótimo 

Em markdown, `>` indica resposta, muito apropriado em nosso contexto
`"` indica citação, muito apropriada no nosso contexto
Estar entre linhas em branco indica separação de itens/parágrafos, facilita a leitura e melhora o visual, muito apropriado ao nosso contexto

Só não sei se itálico se faz necessário, visto que já temos outros indicativos para a mesma coisa. Em nosso contexto, em minha opinião itálico deveria ser usado para dar destaque a palavras específicas que merecem esse destaque/diferencial

Dito isto, a adição ou remoção de um `>` no início da frase, ou aspas ou itálico no entorno da frase não prejudicariam scripts. Na verdade, todo item sintático pode melhorá-lo, pois dá mais contexto para analisar a frase, desde que esse contexto tenha um significado padronizado
